import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import NavbarWrapper from "./component/navbarWrapper";
import TimeWrapper from "./component/timeWrapper";

import { TimeDateProvider } from "./component/global/TimeDateContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aprendéce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex antialiased">
       
        <TimeDateProvider>
          {/* <ContentProvider> */}
            <NavbarWrapper />
            <div className="flex flex-col flex-1">
              <TimeWrapper />
              <main className="flex-1">{children}</main>
            </div>
            <ToastContainer />
          {/* </ContentProvider> */}
        </TimeDateProvider>
      </body>
    </html>
  );
}